{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- protection contre l'injection dans les args\n",
    "- field validator pour personnalise les conditions d'acceptation (ex. avoir un champs positif si c'est un nombre, avoir un @ si on veut un email)\n",
    "- sérialisation/désérialisation en JSON"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 validation error for Utilisateur\n",
      "age\n",
      "  Value error, L'âge doit être positif [type=value_error, input_value=-1, input_type=int]\n",
      "    For further information visit https://errors.pydantic.dev/2.10/v/value_error\n"
     ]
    }
   ],
   "source": [
    "# DEMO - VALIDATEUR DE CHAMPS\n",
    "from pydantic import BaseModel, Field, ValidationError, field_validator\n",
    "\n",
    "class Utilisateur(BaseModel):\n",
    "    nom: str\n",
    "    age: int\n",
    "\n",
    "    @field_validator(\"age\")\n",
    "    def verifier_age(cls, age):\n",
    "        if age < 0:\n",
    "            raise ValueError(\"L'âge doit être positif\")\n",
    "        return age\n",
    "\n",
    "# Utilisation\n",
    "try:\n",
    "    utilisateur = Utilisateur(nom=\"Alice\", age=-1)\n",
    "except ValidationError as e:\n",
    "    print(e)  # Affiche: 1 validation error for Utilisateur\n",
    "              # age\n",
    "              #   L'âge doit être positif (type=value_error)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "id=123 nom='John Doe' age=30\n"
     ]
    },
    {
     "ename": "ValidationError",
     "evalue": "1 validation error for Utilisateur\nage\n  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='bool', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/int_parsing",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 11\u001b[0m\n\u001b[1;32m      9\u001b[0m utilisateur \u001b[38;5;241m=\u001b[39m Utilisateur(\u001b[38;5;28mid\u001b[39m\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m123\u001b[39m\u001b[38;5;124m'\u001b[39m, age\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m30\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28mprint\u001b[39m(utilisateur)\n\u001b[0;32m---> 11\u001b[0m utilisateur \u001b[38;5;241m=\u001b[39m \u001b[43mUtilisateur\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mid\u001b[39;49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m123\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mage\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mbool\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m     12\u001b[0m \u001b[38;5;28mprint\u001b[39m(utilisateur)\n",
      "File \u001b[0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/pydantic/main.py:214\u001b[0m, in \u001b[0;36mBaseModel.__init__\u001b[0;34m(self, **data)\u001b[0m\n\u001b[1;32m    212\u001b[0m \u001b[38;5;66;03m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[39;00m\n\u001b[1;32m    213\u001b[0m __tracebackhide__ \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[0;32m--> 214\u001b[0m validated_self \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m__pydantic_validator__\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mvalidate_python\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mself_instance\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m    215\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m validated_self:\n\u001b[1;32m    216\u001b[0m     warnings\u001b[38;5;241m.\u001b[39mwarn(\n\u001b[1;32m    217\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mA custom validator is returning a value other than `self`.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m    218\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mReturning anything other than `self` from a top level model validator isn\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mt supported when validating via `__init__`.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    219\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mSee the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m    220\u001b[0m         stacklevel\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m2\u001b[39m,\n\u001b[1;32m    221\u001b[0m     )\n",
      "\u001b[0;31mValidationError\u001b[0m: 1 validation error for Utilisateur\nage\n  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='bool', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/int_parsing"
     ]
    }
   ],
   "source": [
    "# Protection contre l'injection avec convertissage automatique et si pas possible, renvoie l'erreur\n",
    "from pydantic import BaseModel, ValidationError\n",
    "\n",
    "class Utilisateur(BaseModel):\n",
    "    id: int\n",
    "    nom: str = 'John Doe'\n",
    "    age: int\n",
    "\n",
    "# Utilisation\n",
    "utilisateur = Utilisateur(id='123', age='30')\n",
    "print(utilisateur)\n",
    "utilisateur = Utilisateur(id='123', age='bool')\n",
    "print(utilisateur)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\"id\":123,\"nom\":\"John Doe\",\"age\":30}\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "Utilisateur(id=123, nom='John Doe', age=30)"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Sérialisation/Désérialisation\n",
    "utilisateur = Utilisateur(id='123', age='30')\n",
    "json_serialize = utilisateur.model_dump_json() # Sérialisation\n",
    "print(utilisateur.model_dump_json())\n",
    "Utilisateur.model_validate_json(json_serialize) # Désérialisation"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
